---
title: "Spatial Data Analysis in R: Lightning Demo!"
author: "Jeff W. Hollister"
date: "11/3/2015"
output: html_document
---

Free and open source software solutions for GIS have come a long way in the last several years as tools to handle file I/O, vector analysis, and raster processing have matured.  Built on top of many of these libraries are some farily well known options and include [QGIS](http://www.qgis.org/en/site/), [GRASS](https://grass.osgeo.org/), and [PostGIS](http://postgis.net/).  During this same time, we have seen the rise of the [R Language for Statistical Computing](https://www.r-project.org/) and not to be left behind many of the same libraries are now supported in R.  So given all of these options, plus the tools many use provided by [esri](https://www.esri.com) there is a rich ecosystem of options for GIS analysts.  

The purpose of this lightning demo is to provide a small taste of GIS capabilities that are available in R.  I will run through the set-up required to get going, show examples of reading in and exploring both raster and vector, do some simple analysis, and show some visualization options.  As this is a demo, and supposed to be done in 5 minutes, I will likely fail miserably at this.  Becuase of that, I have created this page that has all of what I wanted to show in one place so when things go off the ralis, you can follow along later.

**Note: this demo assumes a minimum level of familiarity with R**

##Get R set up

##Read in data

##Explore that data

##Analyze it

##Visualize it



